version: '3.8'

services:
  activepieces:
    image: activepieces/activepieces:latest
    container_name: activepieces
    restart: unless-stopped
    ports:
      - "80"
    depends_on:
      - redis
    volumes:
      - activepieces_data:/root/.activepieces
    networks:
      - activepieces
      - dokploy-network
    environment:
      - AP_FRONTEND_URL=${AP_FRONTEND_URL}
      - AP_ENVIRONMENT=${AP_ENVIRONMENT:-prod}
      - AP_DB_TYPE=${AP_DB_TYPE}
      - AP_POSTGRES_HOST=${AP_POSTGRES_HOST}
      - AP_POSTGRES_PORT=${AP_POSTGRES_PORT}
      - AP_POSTGRES_DATABASE=${AP_POSTGRES_DATABASE}
      - AP_POSTGRES_USERNAME=${AP_POSTGRES_USERNAME}
      - AP_POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
      - AP_POSTGRES_USE_SSL=${AP_POSTGRES_USE_SSL}
      - AP_QUEUE_MODE=${AP_QUEUE_MODE}
      - AP_REDIS_HOST=${AP_REDIS_HOST}
      - AP_REDIS_PORT=${AP_REDIS_PORT}
      - AP_REDIS_PASSWORD=${AP_REDIS_PASSWORD}
      - AP_SECRET=${AP_SECRET}
      - AP_ENCRYPTION_KEY=${AP_ENCRYPTION_KEY}
      - AP_FILE_STORAGE_LOCATION=${AP_FILE_STORAGE_LOCATION}
      - AP_S3_ENDPOINT=${AP_S3_ENDPOINT}
      - AP_S3_BUCKET=${AP_S3_BUCKET}
      - AP_S3_ACCESS_KEY_ID=${AP_S3_ACCESS_KEY_ID}
      - AP_S3_SECRET_ACCESS_KEY=${AP_S3_SECRET_ACCESS_KEY}
      - AP_S3_REGION=${AP_S3_REGION}
      - AP_FLOW_WORKER_CONCURRENCY=${AP_FLOW_WORKER_CONCURRENCY:-10}
      - AP_SCHEDULED_WORKER_CONCURRENCY=${AP_SCHEDULED_WORKER_CONCURRENCY:-5}
      - AP_EXECUTION_MODE=${AP_EXECUTION_MODE:-SANDBOXED}
      - AP_SIGN_UP_ENABLED=${AP_SIGN_UP_ENABLED:-true}
      - AP_TELEMETRY_ENABLED=${AP_TELEMETRY_ENABLED:-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: activepieces_redis
    restart: unless-stopped
    command: redis-server --requirepass ${AP_REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - activepieces
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  activepieces_data:
    driver: local
  redis_data:
    driver: local

networks:
  activepieces:
    driver: bridge
  dokploy-network:
    external: true
